# Generated by Django 4.2.6 on 2023-10-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=200)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.node')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tax.node')),
                ('url', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tax.node')),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
    ]
