# Generated by Django 4.2.6 on 2023-10-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='pid',
            new_name='p',
        ),
    ]
